### PR TITLE
expand the task list images when clicked.

### PR DESCRIPTION
**Pull request by nherder41**
Images within the task list now expand and open to a new activity.  I have added what an expanded images looks like below:
screenshot_20181116-144532

### CODE REVIEW

**Comment by nherder41** [comment]
some future features that this doesn't include would be to allow the user to swipe left or right between expanded images.

**Comment by rkj4theKnight** [comment]
I still think that we need to add the "back" arrow to our activity. I'm not sure if that means we have to switch the activity or if we just add it manually, but I know we did something like that in one of our labs.

**Comment by rlh35** [comment]
I like the full screen view... How do you go back to the regular view? Are users dependent on their device's back button, or are we thinking of implementing a back button somewhere? Can we change what kind of activity we're using so that we have a back button built in?

**Comment by nherder41** [comment]
> I still think that we need to add the "back" arrow to our activity. I'm not sure if that means we have to switch the activity or if we just add it manually, but I know we did something like that in one of our labs.

ahh yeah we should add that.  I think we should merge this for now, because it's a good skeleton for what we want.  We will definitely have to make another branch to fine tune the details, add a back button, and make the UI look better.

**Comment by rlh35** [comment]
I'm going to go ahead and merge this. I don't think there are any significant issues with this, just things to address for the next commits.

**Pull request merged**
